name: Publish

on:
  workflow_call:
    inputs:
      unpublish:
        description: |
          Unpublish the extension before attempting to publish the current version.
          Useful for dev and QA environments where you don't care about the consistency of a published version
        required: false
        type: boolean
        default: false
      overrides-file:
        description: "filepath for overrides.json file to override vss-extension defaults"
        required: true
        type: string
      artifact-id:
        description: "artifact-id for the index.js file"
        required: true
        type: string
      environment:
        description: "github environment to run in"
        required: true
        type: string
      additional-flags:
        description: "additional flags to provide to the tfx publish command"
        required: false
        type: string
        default: ""
    secrets:
      token:
        description: "Token to use to publish to the marketplace"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Download Build
        uses: actions/download-artifact@v5
        with:
          artifact-ids: ${{ inputs.artifact-id }}
          path: ./nowsecure

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ./nowsecure

      - name: Install Dependencies
        working-directory: ./nowsecure
        run: npm ci

      - name: Install TFX
        run: npm install -g tfx-cli

      - name: Unpublish Extension
        if: ${{ inputs.unpublish }}
        run: |
          tfx extension unpublish \
              --publisher "$(jq -r '.publisher' < ${{ inputs.overrides-file }})" \
              --extension-id "$(jq -r '.id' < ${{ inputs.overrides-file }})" \
              --token ${{ secrets.token }}

      - name: Publish Extension
        run: |
          tfx extension publish \
              --manifest-globs vss-extension.json \
              --overrides-file ${{ inputs.overrides-file }} \
              --token ${{ secrets.token }} \
              ${{ inputs.additional-flags }}
